import { Streamdown } from 'streamdown'
import { useAppConfig } from '../config'

const HELP = (appName: string, kbLabel: string) => `
# ${appName}

${appName} is an interface for working with a knowledge base: the documents, images, spreadsheets, and code that a team accumulates, indexed so that both people and AI can find and use them. It pairs a chat assistant that is grounded in the corpus with direct tools for browsing, searching, querying, and adding material. It also connects to the ACTIVATE platform, so the assistant can reason over the workflows registered in the account, preview them as DAGs, and run and monitor them when asked.

The intent is an interaction layer for AI-driven engineering: one place where the knowledge base, the retrieval layer, the models, and the execution layer meet. The assistant is not a general chatbot with a logo on it; every substantive answer is built by searching and reading the actual corpus, with file paths cited so claims can be checked.

## Chat

Ask questions in plain language. The assistant searches the knowledge base (full text and semantic), reads the files that matter, and cites the paths it used. It also knows the platform:

- **Workflow advice**: it has the account's workflow catalog with descriptions and tags, and can recommend which workflows fit a task or could be assembled together.
- **Preview before running**: ask to see a workflow and it renders the DAG in the Library pane. Runs are validated with a dry run first, and a real run is launched only when you explicitly ask.
- **Monitoring**: it can list recent runs and inspect one, including errors and log tails.
- **Show me**: ask it to display any file, image, or workflow graph and the Library viewer opens it.

Conversations are kept in your browser. The model selector at the top of the chat chooses which AI model answers.

## Library

The file tree of the knowledge base. Click a file to view it: markdown and code render directly, images and PDFs show the original, and office documents are converted to a PDF preview. The **Indexed text** tab on binary files shows exactly what the search index holds for that file, which for images is OCR text plus a model-written description.

Adding material:

- **Drag and drop** files or whole folders onto the tree, or use the **Add** button. The destination folder is configurable and created on demand.
- **Add by URL**: web pages are fetched and reduced to text with the source recorded; PDFs are saved as-is.
- Everything added is searchable in about a second.
- **Delete** removes a file from the knowledge base and from the index.

Files that arrive outside this interface (copied in, generated by scripts) are picked up automatically by a background sync within a few minutes, or immediately with **sync now** in the sidebar.

## Search

One box, three retrieval modes run together: full text (exact words, including text inside DOCX, PDF, PPTX, and text found in images), semantic (meaning-based, so related phrasing matches), and filename. Each result is labeled with the mode that found it. Click a result to open it in the Library.

## Query

Structured questions about the corpus itself, answered from the file index rather than file contents:

- **Canned queries**: largest files, most recently modified, oldest, changed in the last N days, totals by extension, biggest directories.
- **Builder**: compose your own from filters (name, path, extension, size, date, text match), grouping, sorting, and a subtree scope.
- **SQL**: raw read-only SELECT statements over the index tables, for those who know the schema.
- **Saved queries**: name any query and rerun it later with one click.

Queries run across hundreds of per-directory databases in parallel and typically return in tens of milliseconds.

## How the index works

The knowledge base is indexed with GUFI, the Grand Unified File Index from Los Alamos National Laboratory: a tree of small databases mirroring the directory structure, one per folder, holding file metadata plus extracted text and embedding vectors. Because the index mirrors the filesystem, access control is inherited from the filesystem itself. Text is extracted from every supported format (office documents, PDFs, presentations, spreadsheets, images via OCR and vision-model description) and embedded for semantic search. Additions re-index only the touched folder, which is why new material is searchable in about a second.

The corpus root for this deployment is **${kbLabel}**. The sidebar footer shows the index size and the time of the last background sync.
`

export function HelpView() {
  const cfg = useAppConfig()
  return (
    <div className="help-view">
      <div className="help-body card">
        <div className="md-body"><Streamdown>{HELP(cfg.appName, cfg.kbLabel)}</Streamdown></div>
      </div>
    </div>
  )
}
