#!/usr/bin/env python3
"""Derive the turnkey CFD training workflow from deploy/workflow.yaml.

Prints a yaml where a site preset is baked in as the plain form
defaults: scheduler placement on, container source, the model serve, and
the starter corpus. Push the output to a platform workflow record per
deploy/COMPUTE.md's stored-yaml procedure.

    make_cfd_training_yaml.py --preset site-preset.yaml [workflow.yaml] \
        [--shared-dir DIR]

--preset is a file holding {inputs: {<group>: {<field>: <value>}}} with
the site's values (resource-specific paths, accounts, model choice); it
lives with the site's operations notes, not in this repository.

--shared-dir points the images, model, and starter corpus at one
read-only copy on the resource, so a class of trainees launches without
each pulling the images and model weights again. The directory holds
containers/studio.sif, containers/vllm.sif, models/<model dir name>,
and the starter corpus tarball.
"""
import sys
import yaml

HEADER = """
# Generated by deploy/make_cfd_training_yaml.py from deploy/workflow.yaml
# plus a site preset. Every deployment value is a form default here, so a
# launch needs only the resource, account, and QOS. Site-specific paths in
# this file are deliberate: it is the copy people add from the repository
# and run as is.
#
# Regenerate after changing deploy/workflow.yaml; do not hand-edit.
"""

argv = sys.argv[1:]
shared = None
preset_file = None
if '--preset' in argv:
    i = argv.index('--preset')
    preset_file = argv[i + 1]
    del argv[i:i + 2]
if '--shared-dir' in argv:
    i = argv.index('--shared-dir')
    shared = argv[i + 1].rstrip('/')
    del argv[i:i + 2]
src = argv[0] if argv else 'deploy/workflow.yaml'
d = yaml.safe_load(open(src))

ins = d['on']['execute']['inputs']
if not preset_file:
    sys.exit('a --preset file is required; see the module docstring')
preset = yaml.safe_load(open(preset_file))['inputs']

for group, values in preset.items():
    for key, val in values.items():
        ins[group]['items'][key]['default'] = val

# The form opens compact: the scheduler group carries the two fields a
# first launch needs; everything else expands on demand.
for group, item in ins.items():
    if isinstance(item, dict) and item.get('type') == 'group':
        item['collapsed'] = group not in ('resource_and_execution', 'slurm')

if shared:
    model_name = ins['model_settings']['items']['model_dir']['default'].rsplit('/', 1)[-1]
    ins['app_settings']['items']['image_path']['default'] = shared + '/containers/studio.sif'
    ins['model_settings']['items']['vllm_image']['default'] = shared + '/containers/vllm.sif'
    ins['model_settings']['items']['model_dir']['default'] = shared + '/models/' + model_name
    ins['kb_settings']['items']['starter_bundle']['default'] = shared + '/cfd-starter-kb.tar.gz'
ins['session_settings']['items']['session_name']['tooltip'] = (
    'Platform session for the web interface, per user, kept across relaunches. '
    'Change it to run more than one studio.')

print(HEADER.strip())
yaml.safe_dump(d, sys.stdout, sort_keys=False, width=100, allow_unicode=True)
